"""CodeMentor Agent — 代码生成器。

策略：采用"AST → Python 源码"单遍直通（省去 IR 中间步骤以提速），
保留 IR 抽象层（ir.py）供未来优化（如 SSA + 字节码 VM）。

支持两个 codegen target：
- "python"：生成 Python 源码，复用现有 PythonRuntime 执行（零额外运行时）
- "bytecode"：生成自定义栈式字节码（预留，当前 NotImplementedError）

字符串安全转义：所有字符串字面量经 repr() 转义，杜绝字符串内代码注入
（即使源码字符串中含有 Python 代码片段，也无法逃逸出字符串字面量）。

依据：DOC-05 §3.3 代码生成器
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional

from compiler.ast_nodes import (
    Program, Block, NumberLit, StringLit, BooleanLit, VarDecl, VarRef,
    Assign, BinaryOp, UnaryOp, Call, FuncDecl, If, While, Return, ExprStmt, Param,
    Node,
)
from compiler.diagnostics import CompileError, ErrorCode


class CodegenError(CompileError):
    """代码生成错误（遇到不支持的节点）。"""
    def __init__(self, message: str, line: int = 0, column: int = 0):
        super().__init__(message, line, column, ErrorCode.CG_UNSUPPORTED_NODE)


class CodegenTarget(ABC):
    """代码生成目标基类。"""

    @abstractmethod
    def emit(self, ast: Program) -> str:
        """生成目标代码字符串。"""


class PythonCodegen(CodegenTarget):
    """AST → Python 源码。

    设计要点：
    - 每个语句独占一行，缩进随嵌套层级递增
    - func 声明翻译为 Python def
    - print 内建映射到 Python print
    - 字符串字面量用 repr() 转义（防注入核心）
    - 数字统一为 Python 数字字面量
    """

    # MiniLang 运算符 → Python 运算符（大部分相同，and/or/not 一致）
    _OP_MAP = {
        "and": "and", "or": "or",
        "+": "+", "-": "-", "*": "*", "/": "/", "%": "%",
        "==": "==", "!=": "!=", "<": "<", ">": ">", "<=": "<=", ">=": ">=",
    }

    def __init__(self) -> None:
        self._lines: list[str] = []
        self._indent: int = 0

    def emit(self, ast: Program) -> str:
        self._lines = []
        self._indent = 0
        # 文件头注释（标注来源，便于调试）
        self._lines.append("# -*- coding: utf-8 -*-")
        self._lines.append('# Generated by CodeMentor MiniLang compiler (target=python)')
        for stmt in ast.statements:
            self._gen_node(stmt)
        return "\n".join(self._lines) + "\n"

    # ------------------------------------------------------------------ #
    # 语句生成
    # ------------------------------------------------------------------ #

    def _gen_node(self, node: Optional[Node]) -> str:
        """生成节点对应的代码，返回表达式字符串（语句无返回值）。"""
        if node is None:
            return ""

        if isinstance(node, Program):
            for s in node.statements:
                self._gen_node(s)
            return ""

        if isinstance(node, Block):
            self._indent += 1
            for s in node.statements:
                self._gen_node(s)
            self._indent -= 1
            return ""

        if isinstance(node, VarDecl):
            value = self._gen_expr(node.value)
            self._emit(f"{node.name} = {value}")
            return ""

        if isinstance(node, Assign):
            value = self._gen_expr(node.value)
            self._emit(f"{node.name} = {value}")
            return ""

        if isinstance(node, ExprStmt):
            expr = self._gen_expr(node.expr)
            self._emit(expr)
            return ""

        if isinstance(node, If):
            cond = self._gen_expr(node.condition)
            self._emit(f"if {cond}:")
            if node.then_body is not None and node.then_body.statements:
                self._gen_node(node.then_body)
            else:
                self._indent += 1
                self._emit("pass")
                self._indent -= 1
            if node.else_body is not None:
                self._emit("else:")
                if node.else_body.statements:
                    self._gen_node(node.else_body)
                else:
                    self._indent += 1
                    self._emit("pass")
                    self._indent -= 1
            return ""

        if isinstance(node, While):
            cond = self._gen_expr(node.condition)
            self._emit(f"while {cond}:")
            if node.body is not None and node.body.statements:
                self._gen_node(node.body)
            else:
                self._indent += 1
                self._emit("pass")
                self._indent -= 1
            return ""

        if isinstance(node, FuncDecl):
            params = ", ".join(p.name for p in node.params)
            self._emit(f"def {node.name}({params}):")
            if node.body is not None and node.body.statements:
                self._gen_node(node.body)
            else:
                self._indent += 1
                self._emit("pass")
                self._indent -= 1
            return ""

        if isinstance(node, Return):
            if node.value is not None:
                value = self._gen_expr(node.value)
                self._emit(f"return {value}")
            else:
                self._emit("return")
            return ""

        raise CodegenError(f"不支持的语句节点: {type(node).__name__}",
                           line=node.line, column=node.column)

    # ------------------------------------------------------------------ #
    # 表达式生成
    # ------------------------------------------------------------------ #

    def _gen_expr(self, node: Optional[Node]) -> str:
        if node is None:
            return "None"

        if isinstance(node, NumberLit):
            # 整数优化
            if node.value.is_integer():
                return str(int(node.value))
            return repr(node.value)

        if isinstance(node, StringLit):
            # 关键安全点：repr() 转义所有特殊字符，杜绝字符串内代码注入
            # 额外过滤空字节（Python 源码不允许 \0 字面量）
            safe = node.value.replace("\x00", "")
            return repr(safe)

        if isinstance(node, BooleanLit):
            return "True" if node.value else "False"

        if isinstance(node, VarRef):
            return node.name

        if isinstance(node, BinaryOp):
            left = self._gen_expr(node.left)
            right = self._gen_expr(node.right)
            op = self._OP_MAP.get(node.op, node.op)
            return f"({left} {op} {right})"

        if isinstance(node, UnaryOp):
            operand = self._gen_expr(node.operand)
            if node.op == "not":
                return f"(not {operand})"
            return f"(-{operand})"

        if isinstance(node, Call):
            args = ", ".join(self._gen_expr(a) for a in node.args)
            return f"{node.callee}({args})"

        raise CodegenError(f"不支持的表达式节点: {type(node).__name__}",
                           line=node.line, column=node.column)

    # ------------------------------------------------------------------ #
    # 辅助
    # ------------------------------------------------------------------ #

    def _emit(self, line: str) -> None:
        """写入一行（带缩进）。"""
        self._lines.append("    " * self._indent + line)


class BytecodeCodegen(CodegenTarget):
    """字节码 codegen（预留，v2 实现）。

    设计为栈式 VM 指令：PUSH, ADD, CALL, JMP 等。
    当前未实现，调用 emit 抛 NotImplementedError。
    """

    def emit(self, ast: Program) -> str:
        raise NotImplementedError("Bytecode codegen 尚未实现，请使用 target='python'")


# --------------------------------------------------------------------------- #
# 工厂
# --------------------------------------------------------------------------- #

_CODEGEN_REGISTRY: dict[str, type[CodegenTarget]] = {
    "python": PythonCodegen,
    "bytecode": BytecodeCodegen,
}


def get_codegen(target: str = "python") -> CodegenTarget:
    """按目标获取 codegen 实例。"""
    cls = _CODEGEN_REGISTRY.get(target.lower())
    if cls is None:
        raise CodegenError(f"未知的代码生成目标: {target}")
    return cls()
